name: JOTA Workflow

on:
  push:
    branches:
      - dojo_ci_20240930
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout do código
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest pylint

            - name: Linter do código
              run: pylint ./tdd_vendas
                
            - name: run pytest
              run: pytest